[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
pwhash = "1.0.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
chrono ={version = "0.4.38",features = ["serde"]}