[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
shared = { path = "../shared" }
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
